'use client';

import React, { useState, useEffect } from 'react';
import {
  X,
  Sparkles,
  Award,
  Download,
  Printer,
  Copy,
  Check,
  FileText,
  AlertCircle,
} from 'lucide-react';

interface AiReportCardModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const AiReportCardModal: React.FC<AiReportCardModalProps> = ({ isOpen, onClose }) => {
  const [reportText, setReportText] = useState<string | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);

  const generateReportCard = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/gemini/insights', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'report-card' }),
      });
      const data = await res.json();
      setReportText(data.text || 'Report Card generated successfully.');
    } catch (err) {
      console.error('Report Card Error:', err);
      setReportText('Failed to generate AI report card.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen && !reportText && !loading) {
      const timer = setTimeout(() => {
        generateReportCard();
      }, 0);
      return () => clearTimeout(timer);
    }
  }, [isOpen, reportText, loading]);

  if (!isOpen) return null;

  const handleCopy = () => {
    if (reportText) {
      navigator.clipboard.writeText(reportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white rounded-2xl max-w-4xl w-full border border-slate-200 shadow-2xl overflow-hidden my-8 max-h-[92vh] flex flex-col">
        {/* Modal Header */}
        <div className="bg-slate-900 text-white p-6 flex items-center justify-between border-b border-slate-800 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 flex items-center justify-center">
              <Award className="w-5 h-5 text-emerald-400" />
            </div>
            <div>
              <h2 className="text-lg font-extrabold text-white">India Annual Global Performance Report Card</h2>
              <p className="text-xs text-slate-400">Generated by Gemini 3.1 Pro Reasoning Engine</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              disabled={!reportText}
              className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs font-medium flex items-center gap-1.5 transition-colors disabled:opacity-50"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>

            <button
              onClick={handlePrint}
              disabled={!reportText}
              className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs font-medium flex items-center gap-1.5 transition-colors disabled:opacity-50"
            >
              <Printer className="w-3.5 h-3.5 text-slate-300" />
              <span>Print</span>
            </button>

            <button
              onClick={onClose}
              className="p-2 rounded-xl bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700 border border-slate-700 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Modal Content */}
        <div className="p-6 overflow-y-auto flex-1">
          {loading ? (
            <div className="py-20 text-center space-y-4">
              <div className="w-12 h-12 rounded-full border-4 border-emerald-500 border-t-transparent animate-spin mx-auto" />
              <div className="text-sm font-bold text-slate-800">
                Gemini AI Reasoning Engine is Analyzing 60+ Global Indicators...
              </div>
              <p className="text-xs text-slate-500 max-w-md mx-auto">
                Evaluating macro GDP growth, digital public infrastructure, climate performance, press freedom, HDI, and state capacity.
              </p>
            </div>
          ) : (
            <div className="prose prose-slate max-w-none text-xs text-slate-800 leading-relaxed space-y-4 bg-slate-50 p-6 rounded-2xl border border-slate-200 whitespace-pre-line">
              {reportText}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
